name: marvel_api
description: marvel api
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.0.2
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  flutter_mobx: ^2.0.4
  # Network
  retrofit: ^3.0.0
  dio: ^4.0.3
  # JSON Serializer
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  retrofit_generator: any
  flutter_localizations:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/png/
flutter_intl:
  enabled: true
